package com.mattjesmc.armorpieces.identity;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.mattjesmc.armorpieces.ArmorPieces;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import net.minecraft.network.chat.Component;
import org.jspecify.annotations.Nullable;

/**
 * Names the pack an id went to, for an id that is not installed - and for nothing else.
 *
 * <p><b>Why a table exists again.</b> {@link Identified#formerIds()} lives INSIDE the pack that took
 * the piece, so a pack that is not installed declares nothing. With nothing installed
 * {@code armorpieces:tusks} is a string in the mod's own namespace and the namespace names nobody,
 * which is exactly the player this has to help. So the jar ships
 * {@code assets/armorpieces/compat/moved.json}, generated by {@code tools/build_moved_index.py} out
 * of the same {@code former_ids} declarations, and checked in the gate's tier 0.
 *
 * <p><b>It is a label, never a rebind.</b> Nothing resolves through here. The registry wins, then
 * {@code former_ids}, then the uid - {@code docs/plans/compatibility.md} section 2.3 - and this is
 * asked only about an id that has already failed every one of those. That is what makes a generated
 * table safe: a stale row costs a wrong pack NAME on a tooltip, where a stale alias would cost a
 * wrong PIECE in a save.
 *
 * <p><b>Two ways to name a pack, and the second needs no row.</b> An id whose namespace is already a
 * pack's - {@code armorpieces_hunt:something_new}, under a pack simply not installed - names its own
 * pack; only an id under the mod's OWN namespace, written before the split moved it, needs the table.
 * Both end at a lang key on the namespace, so a pack's name translates and this class never holds one.
 *
 * <p><b>Why the file also lists the namespaces.</b> Whether {@code pack.<namespace>} exists cannot be
 * asked at runtime: {@code /armorpieces missing} runs on a dedicated server, whose {@code Language}
 * holds vanilla's keys and none of the mod's, so a lookup there names nothing or prints a raw key at
 * an operator. The generator reads the list out of the mod's own {@code en_us.json} instead, which
 * also makes the answer identical on both sides.
 *
 * <p>An id nothing here can place is shown as itself, which is the point of section 5.1: a part is
 * three JSON files and a PNG, so a player who cannot get the pack can define the id and have their
 * armor back. The id is the whole input to that.
 */
public final class Moved {
    /** Former id to the id it is now, and the packs that have a name. Read once from the jar. */
    private static final Index INDEX = load();

    private Moved() {}

    /** Where the generated table sits in the jar. Package-private so a test can assert it is there. */
    static final String PATH = "/assets/armorpieces/compat/moved.json";

    /** The table as read. Package-private for the same reason: shipping it is a thing to check. */
    record Index(Map<String, String> moved, Set<String> packs) {
        static final Index NONE = new Index(Map.of(), Set.of());
    }

    /** What was actually read out of the jar, for a test that the jar still carries it. */
    static Index shipped() {
        return INDEX;
    }

    /**
     * Reads the index off the classpath - deliberately NOT through the resource manager.
     *
     * <p>It is not a game resource: a resource pack must not be able to change which pack the mod
     * names, it is wanted before and independently of any reload, and both sides want it (the client
     * draws the tooltip, {@code /armorpieces missing} names packs for an operator). A jar without the
     * file still works; every id simply shows as itself.
     */
    private static Index load() {
        try (InputStream stream = Moved.class.getResourceAsStream(PATH)) {
            if (stream == null) {
                ArmorPieces.LOGGER.warn("[Armor Pieces] No {} in the jar - a missing id will not name "
                    + "a pack. Run python tools/build_moved_index.py.", PATH);
            }
            return parse(stream);
        } catch (final Exception exception) {
            // A label is not worth failing a launch over.
            ArmorPieces.LOGGER.warn("[Armor Pieces] Could not read {}: {}", PATH, exception.toString());
            return Index.NONE;
        }
    }

    /**
     * The table, or an empty one for anything that is not a table.
     *
     * <p>Separate from {@link #load} and package-private so a test can hand it the two cases a built
     * jar is not supposed to produce - the file absent, and the file unreadable - without a
     * classloader. Both must degrade to "every id is shown as itself" rather than to a crash: this is
     * a label on a tooltip, and a mod that will not launch because a label is missing is worse than
     * every problem it solves.
     */
    static Index parse(final @Nullable InputStream stream) {
        if (stream == null) {
            return Index.NONE;
        }
        final JsonElement root;
        try {
            root = JsonParser.parseReader(new InputStreamReader(stream, StandardCharsets.UTF_8));
        } catch (final Exception exception) {
            return Index.NONE;
        }
        if (!(root instanceof JsonObject object)) {
            return Index.NONE;
        }
        final Map<String, String> moved = new LinkedHashMap<>();
        if (object.get("moved") instanceof JsonObject rows) {
            for (final Map.Entry<String, JsonElement> row : rows.entrySet()) {
                if (row.getValue().isJsonPrimitive()) {
                    moved.put(row.getKey(), row.getValue().getAsString());
                }
            }
        }
        final Set<String> packs = new LinkedHashSet<>();
        if (object.get("packs") instanceof JsonArray listed) {
            for (final JsonElement namespace : listed) {
                if (namespace.isJsonPrimitive()) {
                    packs.add(namespace.getAsString());
                }
            }
        }
        return new Index(Map.copyOf(moved), Set.copyOf(packs));
    }

    /**
     * One line for one id that could not be resolved: the id, and the pack it belongs to when that is
     * knowable.
     *
     * <p>Given something that is not an id at all - the prose {@code ArmorDecorations} falls back to
     * when a socket holds no readable name - it is passed through unchanged.
     */
    public static Component describe(final String id) {
        return pack(id)
            .<Component>map(pack -> Component.translatable(
                "item.armorpieces.missing_in_pack", Component.literal(id), pack))
            .orElseGet(() -> Component.literal(id));
    }

    /**
     * The name of the pack this id belongs to, translated where it is read, or empty when nothing here
     * can place it.
     */
    public static Optional<Component> pack(final String id) {
        final String namespace = namespaceOf(INDEX.moved().getOrDefault(id, id));
        return INDEX.packs().contains(namespace)
            ? Optional.of(Component.translatable("pack." + namespace))
            : Optional.empty();
    }

    private static String namespaceOf(final String id) {
        final int colon = id.indexOf(':');
        return colon <= 0 ? "" : id.substring(0, colon);
    }
}
