package com.mattjesmc.armorpieces.identity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.Optional;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.contents.TranslatableContents;
import org.junit.jupiter.api.Test;

/**
 * The shipped index still places the ids a save can name - {@code docs/plans/compatibility.md} §5.1.
 *
 * <p>What is being defended is the difference between a player who is told "1 not installed" and one
 * who is told which pack to fetch, or which id to write themselves. The index is generated by
 * {@code tools/build_moved_index.py} and gate-checked against the packs, so what these tests add is
 * the reading half: that a jar without the file still works, that an id nothing can place is shown as
 * itself rather than as a raw lang key, and that the namespace path works with no row at all.
 *
 * <p>No game and no registries. {@link Moved} reads one file off the classpath and returns
 * components; that is deliberately all it does, because it is a label and never a rebind.
 */
class MovedIndexTest {
    /** A key rather than rendered text: a test JVM's Language holds vanilla's lines and none of ours. */
    private static String key(final Component component) {
        return component.getContents() instanceof TranslatableContents translatable
            ? translatable.getKey()
            : "";
    }

    /** The split's case: an id a 0.3.0 save wrote, under the mod's own namespace, now in a pack. */
    @Test
    void aMovedIdNamesThePackItWentTo() {
        final Optional<Component> pack = Moved.pack("armorpieces:tusks");
        assertTrue(pack.isPresent(), "the shipped index should place armorpieces:tusks");
        assertEquals("pack.armorpieces_hunt", key(pack.get()),
            "the name is a lang key on the namespace, so it translates where it is read");
    }

    /**
     * The commoner case once the split is finished: a pack that is simply not installed. Its ids are
     * already in its own namespace, so nothing has moved and no row exists - the namespace is the
     * answer, and the listed packs are how the mod knows it can name it.
     */
    @Test
    void anIdInAPackNamespaceNeedsNoRow() {
        final Optional<Component> pack = Moved.pack("armorpieces_hunt:a_piece_that_does_not_exist");
        assertTrue(pack.isPresent(), "the namespace names the pack with no row in the table");
        assertEquals("pack.armorpieces_hunt", key(pack.get()));
    }

    /** Somebody else's pack. The mod has no business inventing a name for it. */
    @Test
    void aStrangerIsShownAsItself() {
        assertTrue(Moved.pack("somepack:crown").isEmpty());
        assertEquals("somepack:crown", Moved.describe("somepack:crown").getString(),
            "the id is the whole instruction to a player who has to write the piece themselves");
    }

    /** An id under the mod's own namespace that never moved: there is no pack to point at. */
    @Test
    void anUnmovedModIdNamesNoPack() {
        assertTrue(Moved.pack("armorpieces:visor").isEmpty());
        assertEquals("armorpieces:visor", Moved.describe("armorpieces:visor").getString());
    }

    /** What {@code ArmorDecorations} passes in when a socket held no readable id at all. */
    @Test
    void proseIsPassedThrough() {
        assertEquals("an unreadable part", Moved.describe("an unreadable part").getString());
    }

    /** A placed id is one component, so the id and the pack name cannot drift apart in a tooltip. */
    @Test
    void aPlacedIdIsOneLine() {
        assertEquals("item.armorpieces.missing_in_pack", key(Moved.describe("armorpieces:tusks")));
    }

    // ---- the table is in the jar --------------------------------------------------------------

    /**
     * <b>The table ships.</b> It is generated into {@code src/main/resources}, so it rides the jar and
     * is read off the classpath - and every other test here would pass just as happily against an
     * absent file if the fallbacks were wrong, because a missing table degrades to "show the id".
     * That is the right behaviour in the game and a blind spot in a test, so the packaging is asserted
     * on its own: the resource is at the path {@link Moved} asks for, and it has both halves in it.
     */
    @Test
    void theTableIsOnTheClasspath() {
        try (InputStream stream = Moved.class.getResourceAsStream(Moved.PATH)) {
            assertNotNull(stream, () -> Moved.PATH + " is not in the jar - processResources dropped it, "
                + "or tools/build_moved_index.py has never been run");
        } catch (final IOException failed) {
            throw new AssertionError(failed);
        }
        assertFalse(Moved.shipped().moved().isEmpty(), "the shipped table names no moved id at all");
        assertFalse(Moved.shipped().packs().isEmpty(), "the shipped table names no pack at all");
    }

    /**
     * Every id the table moves lands in a namespace the table can also NAME. The generator enforces
     * this and the gate runs the generator, but the file is a plain JSON in the source tree: this is
     * the assertion that survives someone editing it by hand.
     */
    @Test
    void everyMovedIdLandsInAPackThatCanBeNamed() {
        for (final Map.Entry<String, String> row : Moved.shipped().moved().entrySet()) {
            assertTrue(Moved.pack(row.getKey()).isPresent(),
                () -> row.getKey() + " moved to " + row.getValue()
                    + ", whose namespace is not in the table's pack list - the tooltip would name nothing");
        }
    }

    /** And every pack it can name has a line in the language file the mod actually ships. */
    @Test
    void everyNamedPackHasALanguageLine() throws IOException {
        final JsonObject lang;
        try (InputStream stream = Moved.class.getResourceAsStream("/assets/armorpieces/lang/en_us.json")) {
            assertNotNull(stream, "the mod's own en_us.json is not on the classpath");
            lang = JsonParser.parseReader(new InputStreamReader(stream, StandardCharsets.UTF_8))
                .getAsJsonObject();
        }
        for (final String namespace : Moved.shipped().packs()) {
            assertTrue(lang.has("pack." + namespace),
                () -> "pack." + namespace + " has no line in en_us.json - a tooltip would print the "
                    + "raw key at a player");
        }
    }

    /**
     * A jar the table is missing from still runs, and so does one where it is corrupt.
     *
     * <p>This is the reason {@code parse} is separate from the classpath read. The table is a LABEL:
     * losing it costs a pack name on a tooltip, and a mod that refuses to launch over a label is worse
     * than every problem the label solves.
     */
    @Test
    void aJarWithoutTheTableStillWorks() {
        assertTrue(Moved.parse(null).moved().isEmpty(), "an absent table should read as an empty one");
        assertTrue(Moved.parse(bytes("not json at all")).packs().isEmpty(),
            "unreadable content should read as an empty table, not throw");
        assertTrue(Moved.parse(bytes("[1, 2, 3]")).moved().isEmpty(),
            "JSON of the wrong shape should read as an empty table");
        assertTrue(Moved.parse(bytes("{}")).packs().isEmpty(), "a table with neither half is empty");
    }

    private static InputStream bytes(final String content) {
        return new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8));
    }
}
