"""Where a part's geometry, data file and sheets live, now that a part need not be the mod's.

The split of 2026-09-07 moved 25 parts out of `src/main/resources` and into `packs/`, and every tool
that had the mod's asset folder written into it went stale the moment it did - seven painters raised
on a geometry file that was no longer there, `trace_geometry.py` refused a part it could not find a
registry entry for, and `check_painters.py`'s trace pass stopped seeing a quarter of the parts
without saying so. The authoring tools are the repository's, not the mod's: a part is authored the
same way wherever it ships.

So "where is `antlers.json`?" is asked here, once, and looked for in the mod first and then in each
pack. The masters do NOT move: `tools/decoration_masters/` is one flat authoring directory keyed by
the part's name, and which pack a part ends up in is a publishing decision made after it is drawn.

**`packs/legacy` is skipped everywhere here, and that is the important line.** The restore pack is
generated by `tools/build_legacy_pack.py` out of the other packs and holds the same 25 parts a
second time, under the mod's own namespace. Nothing may author into it - a master installed there
would be overwritten by the next build while the pack that really owns the part kept the old sheet -
and nothing may check against it, which would report every moved part's failure twice.

A part's name is unique across the mod and the packs - `tools/check_additive.py` is what keeps it
so - which is why one bare name is enough to find it.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MOD = ROOT / "src" / "main" / "resources"
PACKS = ROOT / "packs"
GENERATED = {"legacy"}


def _packs() -> list[Path]:
    if not PACKS.is_dir():
        return []
    return [p for p in sorted(PACKS.iterdir()) if p.is_dir() and p.name not in GENERATED]


def asset_roots() -> list[Path]:
    """Every folder that can hold an `assets/<ns>/` tree, the mod's first."""
    roots = [MOD]
    for pack in _packs():
        for half in (pack / "resourcepack", pack):
            if (half / "assets").is_dir():
                roots.append(half)
                break
    return roots


def data_roots() -> list[Path]:
    """Every folder that can hold a `data/<ns>/` tree, the mod's first."""
    roots = [MOD]
    for pack in _packs():
        for half in (pack / "datapack", pack):
            if (half / "data").is_dir():
                roots.append(half)
                break
    return roots


def all_geometry() -> list[Path]:
    """Every part's geometry file, the mod's and the packs', sorted by the part's name."""
    found: dict[str, Path] = {}
    for root in asset_roots():
        for path in sorted(root.glob("assets/*/armorpieces/decoration/*.json")):
            found.setdefault(path.stem, path)
    return [found[name] for name in sorted(found)]


def all_parts() -> list[Path]:
    """Every part's data file, the mod's and the packs', sorted by the part's name."""
    found: dict[str, Path] = {}
    for root in data_roots():
        for path in sorted(root.glob("data/*/armorpieces/armor_decoration/*.json")):
            found.setdefault(path.stem, path)
    return [found[name] for name in sorted(found)]


def geometry(part: str) -> Path:
    """The geometry file of one part, wherever it ships. Raises if nothing defines it."""
    for root in asset_roots():
        for path in root.glob(f"assets/*/armorpieces/decoration/{part}.json"):
            return path
    raise SystemExit(f"error: no geometry for {part!r} in the mod or any pack under {PACKS}")


def part(name: str) -> Path | None:
    """The data file of one part, wherever it ships, or None if nothing defines it."""
    for root in data_roots():
        for path in root.glob(f"data/*/armorpieces/armor_decoration/{name}.json"):
            return path
    return None


def textures(part_name: str) -> Path:
    """The folder a part's sheets are installed into: the one beside its geometry."""
    return geometry(part_name).parents[2] / "textures" / "entity" / "decoration"
