"""Compose the mod page header banner from an in-game screenshot.

    python tools/make_banner.py run/screenshots/shot.png [--focus 0.65] [--zoom 1.0]
                               [--title "Armor Pieces"] [--tagline "..."] [--out docs/assets/banners/header.png]

The screenshot is cover-cropped to 1200x340 (modpage's header size), a dark
gradient is laid over the left third, and the title and tagline are drawn there.
``--focus`` is the horizontal point of the screenshot (0 = left edge, 1 = right)
to keep centred in the crop; ``--zoom`` > 1 crops tighter. Nothing here is
generated by modpage: it only picks the file up if it exists.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

WIDTH, HEIGHT = 1200, 340
INK = (245, 243, 255)
ACCENT = (0x5B, 0x21, 0xB6)  # the badge colour in modpage.yml
SHADE = (14, 10, 26)


def _font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for name in ("bahnschrift.ttf", "segoeuib.ttf", "arialbd.ttf", "DejaVuSans-Bold.ttf"):
        try:
            f = ImageFont.truetype(name, size)
            if name == "bahnschrift.ttf":
                try:
                    f.set_variation_by_name("Bold")
                except Exception:
                    pass
            return f
        except OSError:
            continue
    return ImageFont.load_default()


def cover(src: Image.Image, focus: float, zoom: float, vfocus: float) -> Image.Image:
    sw, sh = src.size
    scale = max(WIDTH / sw, HEIGHT / sh) * zoom
    img = src.resize((round(sw * scale), round(sh * scale)), Image.LANCZOS)
    w, h = img.size
    cx = min(max(round(w * focus), WIDTH // 2), w - WIDTH // 2)
    cy = min(max(round(h * vfocus), HEIGHT // 2), h - HEIGHT // 2)
    return img.crop((cx - WIDTH // 2, cy - HEIGHT // 2, cx - WIDTH // 2 + WIDTH, cy - HEIGHT // 2 + HEIGHT))


def compose(shot: Path, out: Path, title: str, tagline: str, focus: float, zoom: float,
            vfocus: float, text_width: float) -> None:
    base = cover(Image.open(shot).convert("RGB"), focus, zoom, vfocus).convert("RGBA")

    # Left-side gradient: opaque shade fading to nothing by ``text_width`` of the width.
    grad = Image.new("L", (WIDTH, 1))
    span = max(1, round(WIDTH * text_width))
    for x in range(WIDTH):
        t = min(1.0, x / span)
        grad.putpixel((x, 0), round(235 * (1 - t) ** 1.6))
    grad = grad.resize((WIDTH, HEIGHT))
    shade = Image.new("RGBA", (WIDTH, HEIGHT), SHADE + (0,))
    shade.putalpha(grad)
    base.alpha_composite(shade)

    draw = ImageDraw.Draw(base)
    title_font = _font(96)
    tag_font = _font(26)
    x = 56
    tb = draw.textbbox((0, 0), title, font=title_font)
    th = tb[3] - tb[1]
    tag_lines = _wrap(draw, tagline, tag_font, round(WIDTH * text_width) - x - 24) if tagline else []
    block = th + (16 + len(tag_lines) * 34 if tag_lines else 0)
    y = (HEIGHT - block) // 2 - tb[1]
    draw.text((x + 3, y + 4), title, font=title_font, fill=(0, 0, 0, 160))
    draw.text((x, y), title, font=title_font, fill=INK)
    # accent rule under the title
    ry = y + tb[1] + th + 8
    draw.rectangle([x, ry, x + 140, ry + 5], fill=ACCENT)
    ty = ry + 18
    for line in tag_lines:
        draw.text((x + 2, ty + 2), line, font=tag_font, fill=(0, 0, 0, 140))
        draw.text((x, ty), line, font=tag_font, fill=(226, 222, 245))
        ty += 34

    out.parent.mkdir(parents=True, exist_ok=True)
    base.convert("RGB").save(out, optimize=True)
    print(f"wrote {out} ({WIDTH}x{HEIGHT})")


def _wrap(draw: ImageDraw.ImageDraw, text: str, font, max_w: int) -> list[str]:
    words, lines, cur = text.split(), [], ""
    for w in words:
        trial = (cur + " " + w).strip()
        if draw.textlength(trial, font=font) <= max_w or not cur:
            cur = trial
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("screenshot", type=Path)
    ap.add_argument("--out", type=Path, default=Path("docs/assets/banners/header.png"))
    ap.add_argument("--title", default="Armor Pieces")
    ap.add_argument("--tagline", default="Real geometry on your armor, coloured by trim materials.")
    ap.add_argument("--focus", type=float, default=0.6, help="horizontal point of the shot to centre (0..1)")
    ap.add_argument("--vfocus", type=float, default=0.5, help="vertical point of the shot to centre (0..1)")
    ap.add_argument("--zoom", type=float, default=1.0, help=">1 crops tighter")
    ap.add_argument("--text-width", type=float, default=0.42, help="share of the width shaded for text")
    a = ap.parse_args()
    compose(a.screenshot, a.out, a.title, a.tagline, a.focus, a.zoom, a.vfocus, a.text_width)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
